name: build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test and run
        run: |
          go run ./cmd/golangci-config-generator
          golangci-lint run -v
